name: Check In

on:
  push:
  pull_request:

permissions:
  contents: read

jobs:
  check-in:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version-file: go.mod
          cache: true
      - uses: extractions/setup-just@v4
        with:
          just-version: "1.56.0"
      - run: just test
